-- create USER table
DROP TABLE USER IF EXISTS;

CREATE TABLE USER (
	user_id		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username	varchar(50)	not null,
	password    varchar(50),
	role        varchar(10) not null,
	user_status	varchar(1)  not null,  
    created_dt  timestamp   not null,
    updated_dt  timestamp   not null,
);

ALTER TABLE user ADD CONSTRAINT user_uk UNIQUE (username);
ALTER TABLE user ADD CHECK (role = 'ADMIN' or role = 'USER');
ALTER TABLE user ADD CHECK (user_status = 'A' or user_status = 'I');

-- create EVENT table
DROP TABLE EVENT IF EXISTS;

CREATE TABLE EVENT (
   event_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_type   varchar(20),   
   location     varchar(100),
   description  varchar(100),
   event_dt     timestamp,
   created_dt   timestamp not null,
   updated_dt   timestamp not null
   -- not called out in the spec, might need eventually however...
   -- price        numeric,  
   -- capacity     integer
);

alter table event add check (event_type = 'SPORTING' or event_type = 'CONCERT' or event_type = 'THEATER' );

-- create ORDER table
DROP TABLE CUSTOMER_ORDER IF EXISTS;

CREATE TABLE CUSTOMER_ORDER (      
   order_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id     integer NOT NULL, 
   event_id    integer NOT NULL,
   order_dt    timestamp    NOT NULL,
   num_tickets integer,
   order_status varchar(10),
   created_dt   timestamp not null,
   updated_dt   timestamp not null
);

ALTER TABLE customer_order ADD CHECK (order_status = 'ACTIVE' or order_status = 'CANCELLED');

ALTER TABLE customer_order ADD FOREIGN KEY (user_id) REFERENCES user (user_id);
ALTER TABLE customer_order ADD FOREIGN KEY (event_id) REFERENCES event (event_id);

-- TODO: create a VENUE table to store event location details, 
-- including event sizes. what to do if the size changes based on 
-- the event? e.g. the Garden can hold more people for a concert
-- vs a basketball game due to floor seats...

-- might also want a TICKET table to store event and seating info eventually
